package com.portfolio.backend.entity;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;

/**
 * Represents a project completed by a user.
 */
@Entity
@EntityListeners(AuditingEntityListener.class)
public class Project {

    /**
     * Unique identifier for each project.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the project.
     */
    private String title;

    /**
     * Description of the project.
     */
    private String description;

    /**
     * URL of the project (e.g., a link to a website or GitHub repository).
     */
    private String url;

    /**
     * URL of the image associated with the project.
     * Can be used for display purposes.
     */
    private String imageUrl;

    /**
     * Status of the project (e.g., "In Progress", "Completed").
     */
    private String status;

    /**
     * The creation timestamp of the project.
     * This field is non-editable after the project is created.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreatedDate
    private LocalDateTime createdAt;

    /**
     * The last updated timestamp of the project.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * List of skills related to the project.
     * Many-to-Many relationship between `Project` and `Skill`.
     */
    @ManyToMany
    @JoinTable(name = "project_skill", // Join table linking "project" and "skill"
            joinColumns = @JoinColumn(name = "project_id"), // Column linking the project
            inverseJoinColumns = @JoinColumn(name = "skill_id") // Column linking the skills
    )
    private List<Skill> skills;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<Skill> getSkills() {
        return skills;
    }

    public void setSkills(List<Skill> skills) {
        this.skills = skills;
    }

}