package com.portfolio.backend.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;

/**
 * Represents a project completed by a user.
 */
@Entity
public class Project {

    /**
     * Unique identifier for each project.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Title of the project.
     */
    private String title;

    /**
     * Description of the project.
     */
    private String description;

    /**
     * Short summary used in listing cards.
     */
    private String summary;

    /**
     * Status of the project (e.g., "completed", "in_progress").
     */
    private String status;

    /**
     * Cover image displayed on cards/hero sections.
     */
    private String coverImage;

    /**
     * Additional gallery images for the project.
     */
    @ElementCollection(fetch = jakarta.persistence.FetchType.EAGER)
    @CollectionTable(name = "project_images", joinColumns = @JoinColumn(name = "project_id"))
    @Column(name = "image_url")
    private List<String> images = new ArrayList<>();

    /**
     * Repository URL (GitHub, GitLab...).
     */
    private String repoUrl;

    /**
     * Live demo URL for the project.
     */
    private String liveUrl;

    /**
     * Tags shown as chips on the frontend.
     */
    @ElementCollection(fetch = jakarta.persistence.FetchType.EAGER)
    @CollectionTable(name = "project_tags", joinColumns = @JoinColumn(name = "project_id"))
    @Column(name = "tag")
    private List<String> tags = new ArrayList<>();

    /**
     * Long-form content / case study.
     */
    @Column(columnDefinition = "TEXT")
    private String content;

    @ElementCollection(fetch = jakarta.persistence.FetchType.EAGER)
    @CollectionTable(name = "project_stack", joinColumns = @JoinColumn(name = "project_id"))
    @Column(name = "stack_item")
    private List<String> stack = new ArrayList<>();

    @ElementCollection(fetch = jakarta.persistence.FetchType.EAGER)
    @CollectionTable(name = "project_features", joinColumns = @JoinColumn(name = "project_id"))
    @Column(name = "feature")
    private List<String> features = new ArrayList<>();

    @ElementCollection(fetch = jakarta.persistence.FetchType.EAGER)
    @CollectionTable(name = "project_contributions", joinColumns = @JoinColumn(name = "project_id"))
    @Column(name = "contribution")
    private List<String> contributions = new ArrayList<>();

    @ElementCollection(fetch = jakarta.persistence.FetchType.EAGER)
    @CollectionTable(name = "project_outcomes", joinColumns = @JoinColumn(name = "project_id"))
    @Column(name = "outcome")
    private List<String> outcomes = new ArrayList<>();

    private String client;
    @Column(columnDefinition = "TEXT")
    private String testimonial;
    private String testimonialAuthor;
    private String mood;
    @Column(columnDefinition = "TEXT")
    private String personalNote;
    private String duration;
    private String role;

    /**
     * The creation timestamp of the project.
     * This field is non-editable after the project is created.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * The last updated timestamp of the project.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * List of skills related to the project.
     * Many-to-Many relationship between `Project` and `Skill`.
     */
    @ManyToMany
    @JsonIgnore
    @JoinTable(name = "project_skill", // Join table linking "project" and "skill"
            joinColumns = @JoinColumn(name = "project_id"), // Column linking the project
            inverseJoinColumns = @JoinColumn(name = "skill_id") // Column linking the skills
    )
    private List<Skill> skills = new ArrayList<>();

    @PrePersist
    public void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = LocalDateTime.now();
        }
        this.updatedAt = this.createdAt;
    }

    @PreUpdate
    public void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCoverImage() {
        return coverImage;
    }

    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images != null ? new ArrayList<>(images) : new ArrayList<>();
    }

    public String getRepoUrl() {
        return repoUrl;
    }

    public void setRepoUrl(String repoUrl) {
        this.repoUrl = repoUrl;
    }

    public String getLiveUrl() {
        return liveUrl;
    }

    public void setLiveUrl(String liveUrl) {
        this.liveUrl = liveUrl;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags != null ? new ArrayList<>(tags) : new ArrayList<>();
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public List<String> getStack() {
        return stack;
    }

    public void setStack(List<String> stack) {
        this.stack = stack != null ? new ArrayList<>(stack) : new ArrayList<>();
    }

    public List<String> getFeatures() {
        return features;
    }

    public void setFeatures(List<String> features) {
        this.features = features != null ? new ArrayList<>(features) : new ArrayList<>();
    }

    public List<String> getContributions() {
        return contributions;
    }

    public void setContributions(List<String> contributions) {
        this.contributions = contributions != null ? new ArrayList<>(contributions) : new ArrayList<>();
    }

    public List<String> getOutcomes() {
        return outcomes;
    }

    public void setOutcomes(List<String> outcomes) {
        this.outcomes = outcomes != null ? new ArrayList<>(outcomes) : new ArrayList<>();
    }

    public String getClient() {
        return client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public String getTestimonial() {
        return testimonial;
    }

    public void setTestimonial(String testimonial) {
        this.testimonial = testimonial;
    }

    public String getTestimonialAuthor() {
        return testimonialAuthor;
    }

    public void setTestimonialAuthor(String testimonialAuthor) {
        this.testimonialAuthor = testimonialAuthor;
    }

    public String getMood() {
        return mood;
    }

    public void setMood(String mood) {
        this.mood = mood;
    }

    public String getPersonalNote() {
        return personalNote;
    }

    public void setPersonalNote(String personalNote) {
        this.personalNote = personalNote;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<Skill> getSkills() {
        return skills;
    }

    public void setSkills(List<Skill> skills) {
        this.skills = skills;
    }

}
