package com.portfolio.backend.entity;

import java.util.List;

import jakarta.persistence.Id;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.OneToMany;

/**
 * Represents a role in the application.
 * A role can be assigned to multiple users (e.g., "ADMIN", "USER").
 */
@Entity // Marks this class as a JPA entity to be mapped to a database table.
public class Role {

    /**
     * Unique identifier for each role.
     * Automatically generated by the database using the IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the role, such as "ADMIN" or "USER".
     * This field is used to identify roles within the application.
     */
    private String name;

    /**
     * List of users associated with this role.
     * One-to-Many relationship (a role can be shared by multiple users).
     * The relationship is defined using the "role" field in the `User` class.
     */
    @OneToMany(mappedBy = "role") // Indicates that this is the inverse side of the relationship.
    private List<User> users;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }

}
