package com.portfolio.backend.entity;

import java.time.LocalDateTime;
import java.util.List;

import jakarta.persistence.Id;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.ManyToMany;

/**
 * Represents a skill in the application.
 * Each skill can be associated with multiple projects.
 */
@Entity // Indicates that this class is a JPA entity and will be mapped to a database
        // table.
public class Skill {

    /**
     * Unique identifier for each skill.
     * Automatically generated by the database using the GenerationType.IDENTITY
     * strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the skill (e.g., "Java", "Spring", "React").
     */
    private String name;

    /**
     * Proficiency level of the skill (e.g., "Beginner", "Intermediate",
     * "Advanced").
     */
    private String level;

    /**
     * URL or path of the icon representing the skill.
     * This icon can be displayed in the user interface.
     */
    private String icon;

    /**
     * The creation date of the skill entity.
     * This field is required and cannot be updated after creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * The last updated date of the skill entity.
     * This field is updated whenever a change is made to the skill.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * List of projects associated with this skill.
     * Many-to-Many relationship: A skill can be used in multiple projects,
     * and a project can have multiple skills.
     */
    @ManyToMany(mappedBy = "skills") // Defines that this entity is the inverse side of the relationship with
                                     // "skills" in Project.
    private List<Project> projects;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<Project> getProjects() {
        return projects;
    }

    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

}
